#include "web_ui.h"

const char *web_ui_html(void)
{
    static const char *html =
        "<!doctype html><html><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>prone collector</title>"
        "<style>"
        "body{font-family:sans-serif;background:#f4f5f7;color:#111;margin:0;padding:16px;}"
        ".wrap{max-width:980px;margin:0 auto;display:grid;gap:16px;}"
        ".panel{background:#fff;border-radius:12px;padding:16px;box-shadow:0 2px 10px rgba(0,0,0,.08);}"
        "img{width:100%;background:#111;border-radius:12px;display:block;}"
        ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;}"
        "label{display:block;font-size:14px;margin-bottom:4px;}"
        "input,select,textarea,button{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;box-sizing:border-box;}"
        "button{background:#1d4ed8;color:#fff;border:none;font-weight:700;cursor:pointer;min-height:52px;}"
        ".secondary{background:#475569;}"
        ".danger{background:#b91c1c;}"
        ".row{display:flex;gap:12px;flex-wrap:wrap;}"
        ".row > div{flex:1 1 200px;}"
        ".stream_shell{max-width:420px;margin:0 auto;display:grid;gap:12px;}"
        ".stream_capture{display:grid;grid-template-columns:1fr;gap:10px;}"
        ".stream_frame{max-width:420px;margin:0 auto;}"
        ".status{white-space:pre-wrap;font-family:monospace;font-size:13px;background:#0f172a;color:#e2e8f0;border-radius:8px;padding:12px;}"
        ".result{white-space:pre-wrap;font-family:monospace;font-size:13px;background:#172554;color:#dbeafe;border-radius:8px;padding:12px;min-height:48px;}"
        "</style></head><body><div class='wrap'>"
        "<div class='panel'><div class='stream_shell'>"
        "<h1>学習データ収集</h1>"
        "<div class='stream_capture'>"
        "<button id='capture_button' onclick='captureSample()'>撮影</button>"
        "</div>"
        "<div class='stream_frame'><img id='stream_view' alt='stream'></div>"
        "</div></div>"
        "<div class='panel'><div class='grid'>"
        "<div><label>subject_id</label><input id='subject_id' value='baby_001'></div>"
        "<div><label>session_id</label><input id='session_id' value='baby_001_20260315_am_setup01'></div>"
        "<div><label>location_id</label><input id='location_id' value='loc_01'></div>"
        "<div><label>lighting_id</label><input id='lighting_id' value='light_day'></div>"
        "<div><label>camera_position_id</label><input id='camera_position_id' value='campos_top'></div>"
        "<div><label>annotator_id</label><input id='annotator_id' value='ann_a01'></div>"
        "<div><label>label</label><select id='label'><option value='1'>うつ伏せ</option><option value='0'>非うつ伏せ</option></select></div>"
        "<div><label>学習利用可否</label><select id='is_usable_for_training'><option value='1'>利用可</option><option value='0'>利用不可</option></select></div>"
        "<div><label>exclude_reason</label><select id='exclude_reason'>"
        "<option value=''>空</option><option value='ambiguous_pose'>ambiguous_pose</option>"
        "<option value='face_not_visible'>face_not_visible</option>"
        "<option value='subject_missing'>subject_missing</option>"
        "<option value='multiple_subjects'>multiple_subjects</option>"
        "<option value='motion_blur'>motion_blur</option>"
        "<option value='poor_lighting'>poor_lighting</option>"
        "<option value='annotation_error'>annotation_error</option>"
        "<option value='other'>other</option></select></div>"
        "<div style='grid-column:1/-1'><label>notes</label><textarea id='notes' rows='4'></textarea></div>"
        "</div>"
        "<div class='row' style='margin-top:12px'>"
        "<div><button id='export_button' class='secondary' onclick='exportDataset()'>エクスポート</button></div>"
        "<div><button class='danger' onclick='resetDataset()'>SDカードリセット</button></div>"
        "</div></div>"
        "<div class='panel'><h2>状態</h2><div id='status' class='status'>loading...</div></div>"
        "<div class='panel'><h2>応答</h2><div id='result' class='result'>待機中</div></div>"
        "</div>"
        "<script>"
        "function el(id){return document.getElementById(id);}"
        "function setResult(message){el('result').textContent=message;}"
        "function streamUrl(){return location.protocol+'//'+location.hostname+':81/stream';}"
        "function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}"
        "function triggerDownload(blob,name){"
        "const url=URL.createObjectURL(blob);"
        "const a=document.createElement('a');"
        "a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();"
        "setTimeout(()=>URL.revokeObjectURL(url),30000);"
        "}"
        "async function downloadBlob(url,name){"
        "const r=await fetch(url);"
        "if(!r.ok){throw new Error(url+' '+r.status);}"
        "const blob=await r.blob();"
        "triggerDownload(blob,name);"
        "}"
        "async function fetchManifestPage(page,pageSize){"
        "const r=await fetch('/api/export/manifest?page='+page+'&page_size='+pageSize);"
        "if(!r.ok){throw new Error('manifest '+r.status);}"
        "return await r.json();"
        "}"
        "async function fetchAllManifestItems(){"
        "const pageSize=50;"
        "let page=1;"
        "let items=[];"
        "while(true){"
        "const data=await fetchManifestPage(page,pageSize);"
        "items=items.concat(data.items||[]);"
        "if(!data.has_next){break;}"
        "page+=1;"
        "}"
        "return items;"
        "}"
        "async function refreshStatus(){"
        "try{"
        "const r=await fetch('/api/status');"
        "const j=await r.json();"
        "el('status').textContent=JSON.stringify(j,null,2);"
        "}catch(e){"
        "el('status').textContent='status 取得失敗\\n'+String(e);"
        "}"
        "}"
        "function payload(){return {"
        "subject_id:el('subject_id').value.trim(),session_id:el('session_id').value.trim(),location_id:el('location_id').value.trim(),"
        "lighting_id:el('lighting_id').value.trim(),camera_position_id:el('camera_position_id').value.trim(),"
        "annotator_id:el('annotator_id').value.trim(),label:Number(el('label').value),"
        "is_usable_for_training:Number(el('is_usable_for_training').value),exclude_reason:el('exclude_reason').value.trim(),"
        "notes:el('notes').value};}"
        "async function captureSample(){"
        "const button=el('capture_button');"
        "button.disabled=true;"
        "setResult('撮影リクエスト送信中');"
        "try{"
        "const r=await fetch('/api/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});"
        "const text=await r.text();"
        "setResult('HTTP '+r.status+'\\n'+text);"
        "if(!r.ok){throw new Error('capture failed');}"
        "await refreshStatus();"
        "}catch(e){"
        "setResult(el('result').textContent+'\\n'+String(e));"
        "}finally{"
        "button.disabled=false;"
        "}"
        "}"
        "async function exportDataset(){"
        "const button=el('export_button');"
        "button.disabled=true;"
        "try{"
        "setResult('metadata.csv を取得中');"
        "await downloadBlob('/api/export/metadata','metadata.csv');"
        "const items=await fetchAllManifestItems();"
        "const manifestBlob=new Blob([JSON.stringify({total_samples:items.length,items:items},null,2)],{type:'application/json'});"
        "triggerDownload(manifestBlob,'manifest.json');"
        "for(let i=0;i<items.length;i+=1){"
        "const item=items[i];"
        "setResult('画像を取得中 '+(i+1)+' / '+items.length+'\\n'+item.capture_id);"
        "await downloadBlob('/api/export/image?capture_id='+encodeURIComponent(item.capture_id),item.capture_id+'.jpg');"
        "await sleep(150);"
        "}"
        "setResult('エクスポート完了\\nmetadata.csv, manifest.json, 画像 '+items.length+' 件');"
        "}catch(e){"
        "setResult('エクスポート失敗\\n'+String(e));"
        "}finally{"
        "button.disabled=false;"
        "}"
        "}"
        "async function resetDataset(){"
        "if(!confirm('dataset を削除します'))return;"
        "const r=await fetch('/api/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:'RESET'})});"
        "const text=await r.text();"
        "setResult('HTTP '+r.status+'\\n'+text);"
        "await refreshStatus();"
        "}"
        "el('stream_view').src=streamUrl();"
        "refreshStatus();"
        "</script></body></html>";

    return html;
}
